CREATE TABLE Favorites (
    FavoriteID INT IDENTITY(1,1) PRIMARY KEY,
    UserID nvarchar(450) NOT NULL,
    ReportID INT NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (UserID) REFERENCES AspNetUsers(Id) ON DELETE CASCADE,
    FOREIGN KEY (ReportID) REFERENCES Reports(ReportID) ON DELETE CASCADE
);